--CREATE DATABASE TPC_VARISCOGONZALO

--USE TPC_VARISCOGONZALO

CREATE TABLE CLIENTES(
IDCLIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DNI INT NOT NULL,
TELEFONOFIJO VARCHAR(50) NULL,
TELEFONOCELULAR VARCHAR(50) NOT NULL,
CALLE VARCHAR(50) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL,
FECHANACIMIENTO DATE NULL,
SEXO CHAR(1) NULL,
EMAIL VARCHAR(50) NOT NULL,
CUIT VARCHAR(20) NOT NULL,
ACTIVO BIT NULL
)

GO

CREATE TABLE PROVEEDORES(
IDPROVEEDOR INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
CUIT VARCHAR(20) NOT NULL,
CALLE VARCHAR(50) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL,
ACTIVO BIT NULL
)

GO

CREATE TABLE MARCAS(
IDMARCA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
)

GO

CREATE TABLE TIPOPRODUCTO(
IDTIPOPRODUCTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL
)

GO

CREATE TABLE PRODUCTOS(
IDPRODUCTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDTIPOPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES TIPOPRODUCTO(IDTIPOPRODUCTO),
IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS(IDMARCA),
CODIGO VARCHAR(50) NOT NULL,
PRECIOCOSTO MONEY NOT NULL,
PRECIOVENTA MONEY NOT NULL,
STOCKACTUAL INT NOT NULL,
STOCKMINIMO INT NOT NULL
)

GO

CREATE TABLE PROVEEDORES_X_PRODUCTO(
IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO)
PRIMARY KEY(IDPROVEEDOR,IDPRODUCTO)
)

GO

CREATE TABLE FACTURAS(
IDFACTURA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FECHA DATETIME NOT NULL,
IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE)
)

GO

CREATE TABLE REGISTROCOMPRAS(
IDCOMPRA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FECHA DATETIME NOT NULL,
TOTAL MONEY NOT NULL,
IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
)

GO

CREATE TABLE COMPRAITEMS(
IDCOMPRAITEM INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDCOMPRA INT NOT NULL FOREIGN KEY REFERENCES REGISTROCOMPRAS(IDCOMPRA),
IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO),
CANTIDAD INT NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
PRECIOPARCIAL MONEY NOT NULL
)

GO

CREATE TABLE REGISTROVENTAS(
IDVENTA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
FECHA DATETIME NOT NULL,
TOTAL MONEY NOT NULL,
IDFACTURACION INT NOT NULL FOREIGN KEY REFERENCES FACTURAS(IDFACTURA),
)

GO

CREATE TABLE VENTAITEMS(
IDVENTAITEM INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDVENTA INT NOT NULL FOREIGN KEY REFERENCES REGISTROVENTAS(IDVENTA),
IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO),
CANTIDAD INT NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
PRECIOPARCIAL MONEY NOT NULL
)

GO

CREATE TABLE PERFILESUSUARIOS(
IDPERFILUSUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL
)

GO

CREATE TABLE USUARIOS1(
IDUSUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
PASS VARCHAR(50)NOT NULL,
IDPERFILUSUARIO INT NOT NULL FOREIGN KEY REFERENCES PERFILESUSUARIOS(IDPERFILUSUARIO)
)

CREATE TABLE USUARIOS(
IDUSUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
LOGUIN VARCHAR(50) NOT NULL,
IDPERFILUSUARIO INT NOT NULL FOREIGN KEY REFERENCES PERFILESUSUARIOS(IDPERFILUSUARIO)
)

--PERSONAS
INSERT INTO CLIENTES(NOMBRE,APELLIDO,DNI,TELEFONOFIJO,TELEFONOCELULAR,CALLE,LOCALIDAD,PROVINCIA,FECHANACIMIENTO,SEXO,EMAIL,CUIT,ACTIVO) VALUES('ejemplo','bermudez',33265888,0114455986,1546897555,'GARCIA 779','GARIN','BUENOS AIRES','02/10/1986','m','juancho2003@yahoo.com',20165552362,1)
INSERT INTO CLIENTES(NOMBRE,APELLIDO,DNI,TELEFONOFIJO,TELEFONOCELULAR,CALLE,LOCALIDAD,PROVINCIA,FECHANACIMIENTO,SEXO,EMAIL,CUIT,ACTIVO) VALUES('ejemplo2','bermudez22',932659999,449996,159999955,'felipe 779','escobar','BUENOS AIRES','02/10/1970','f','2003@yahoo.com',20999552362,1)

--PROVEEDORES
INSERT INTO PROVEEDORES(NOMBRE,CUIT,CALLE,LOCALIDAD,PROVINCIA,ACTIVO) VALUES('Ejemplo sa', 209996582,'GARCIA 779','GARIN','BUENOS AIRES',1)
INSERT INTO PROVEEDORES(NOMBRE,CUIT,CALLE,LOCALIDAD,PROVINCIA,ACTIVO) VALUES('Ejemplo2', 20888882,'felix 779','caba','BUENOS AIRES',1)


--MARCAS
INSERT INTO MARCAS(NOMBRE)VALUES('Frititas')
INSERT INTO MARCAS(NOMBRE)VALUES('pepitos')
INSERT INTO MARCAS(NOMBRE)VALUES('ser')

--TIPOPRODUCTO
INSERT INTO TIPOPRODUCTO(NOMBRE) VALUES('Galletas')
INSERT INTO TIPOPRODUCTO(NOMBRE) VALUES('bebidas')
INSERT INTO TIPOPRODUCTO(NOMBRE) VALUES('dulces')

--PRODUCTO
INSERT INTO PRODUCTOS(IDTIPOPRODUCTO,IDMARCA,CODIGO,PRECIOCOSTO,PRECIOVENTA,STOCKACTUAL,STOCKMINIMO) VALUES(1,1,'a',15,20,40,10)
INSERT INTO PRODUCTOS(IDTIPOPRODUCTO,IDMARCA,CODIGO,PRECIOCOSTO,PRECIOVENTA,STOCKACTUAL,STOCKMINIMO) VALUES(2,2,'b',30,40,20,5)


--PROVEEDORES_X_PRODUCTO
INSERT INTO PROVEEDORES_X_PRODUCTO(IDPROVEEDOR, IDPRODUCTO) VALUES(1,1)

--FACTURAS
INSERT INTO FACTURAS(FECHA, IDCLIENTE) VALUES('20/09/2018',1)

--REGISTROCOMPRAS
INSERT INTO REGISTROCOMPRAS(FECHA,TOTAL,IDPROVEEDOR) VALUES('16/09/2018',50,1)

--COMPRAITEMS
INSERT INTO COMPRAITEMS(IDCOMPRA,IDPRODUCTO,CANTIDAD,PRECIOUNITARIO,PRECIOPARCIAL) VALUES(1,1,2,15,15)

--REGISTROVENTAS
INSERT INTO REGISTROVENTAS(IDCLIENTE,FECHA,TOTAL,IDFACTURACION) VALUES(1,'20/09/2018',20,1)

--VENTAITEMS
INSERT INTO VENTAITEMS(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIOUNITARIO,PRECIOPARCIAL) VALUES(1,1,30,20,40)

--PERFILESUSUARIOS
INSERT INTO PERFILESUSUARIOS(NOMBRE)VALUES('ADMINISTRADOR')
INSERT INTO PERFILESUSUARIOS(NOMBRE)VALUES('VENDEDOR')

--USUARIOS
INSERT INTO USUARIOS(LOGUIN,IDPERFILUSUARIO)VALUES('PEPE123',1)

--USUARIO1
INSERT INTO USUARIOS1(NOMBRE,PASS,IDPERFILUSUARIO) VALUES ('ADMIN',123,1)
INSERT INTO USUARIOS1(NOMBRE,PASS,IDPERFILUSUARIO) VALUES ('VENDEDOR',123,2)