--CREATE DATABASE TPC_VARISCOGONZALO

--USE TPC_VARISCOGONZALO

CREATE TABLE PERSONAS(
IDPERSONA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DNI INT NOT NULL,
TELEFONOFIJO VARCHAR(50) NULL,
TELEFONOCELULAR VARCHAR(50) NOT NULL,
IDDOMICILIO INT NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
SEXO CHAR(1) NULL,
EMAIL VARCHAR(50) NOT NULL,
CUIT VARCHAR(20) NOT NULL
)
GO

CREATE TABLE CLIENTES(
IDCLIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDPERSONA INT NOT NULL FOREIGN KEY REFERENCES PERSONAS(IDPERSONA)
)

GO

CREATE TABLE PROVEEDORES(
IDPROVEEDOR INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
CUIT VARCHAR(20) NOT NULL,
IDDOMICILIO INT NOT NULL,
)

GO

CREATE TABLE MARCAS(
IDMARCA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
)

GO

CREATE TABLE STOCK(
IDSTOCK INT NOT NULL PRIMARY KEY IDENTITY(1,1),
ACTUAL INT NOT NULL,
MINIMO INT NOT NULL
)

GO

CREATE TABLE TIPOPRODUCTO(
IDTIPOPRODUCTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL
)

GO

CREATE TABLE PRODUCTOS(
IDPRODUCTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDTIPOPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES TIPOPRODUCTO(IDTIPOPRODUCTO),
IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS(IDMARCA),
CODIGO VARCHAR(50) NOT NULL,
PRECIOCOSTO MONEY NOT NULL,
PRECIOVENTA MONEY NOT NULL,
IDSTOCK INT NOT NULL FOREIGN KEY REFERENCES STOCK(IDSTOCK)
)

GO

CREATE TABLE PROVEEDORES_X_PRODUCTO(
IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO)
PRIMARY KEY(IDPROVEEDOR,IDPRODUCTO)
)

GO

CREATE TABLE FACTURAS(
IDFACTURA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
FECHA DATETIME NOT NULL,
IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE)
)

GO

CREATE TABLE DOMICILIOS(
IDDOMICILIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CALLE VARCHAR(50) NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL,
CP VARCHAR(10) NOT NULL,
PAIS VARCHAR(50) NOT NULL
)

GO

CREATE TABLE REGISTROCOMPRAS(
IDCOMPRA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NUMERO INT NOT NULL,
FECHA DATETIME NOT NULL,
IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
)

GO

CREATE TABLE COMPRAITEMS(
IDCOMPRAITEM INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDCOMPRA INT NOT NULL FOREIGN KEY REFERENCES REGISTROCOMPRAS(IDCOMPRA),
IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO),
CANTIDAD INT NOT NULL,
PRECIOCOMPRA MONEY NOT NULL
)

GO

CREATE TABLE REGISTROVENTAS(
IDVENTA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NUMERO INT NOT NULL,
IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
FECHA DATETIME NOT NULL,
TOTAL MONEY NOT NULL,
IDFACTURACION INT NOT NULL FOREIGN KEY REFERENCES FACTURAS(IDFACTURA),
)

GO

CREATE TABLE VENTAITEMS(
IDVENTAITEM INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDVENTA INT NOT NULL FOREIGN KEY REFERENCES REGISTROVENTAS(IDVENTA),
IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO),
CANTIDAD INT NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
PRECIOPARCIAL MONEY NOT NULL
)

GO

CREATE TABLE REGISTROCOMPRAS_X_COMPRAITEMS(
IDCOMPRA INT NOT NULL FOREIGN KEY REFERENCES REGISTROCOMPRAS(IDCOMPRA),
IDCOMPRAITEM INT NOT NULL FOREIGN KEY REFERENCES COMPRAITEMS(IDCOMPRAITEM),
PRIMARY KEY(IDCOMPRA,IDCOMPRAITEM)
)

GO

CREATE TABLE REGISTROVENTAS_X_VENTAITEMS(
IDVENTA INT NOT NULL FOREIGN KEY REFERENCES REGISTROVENTAS(IDVENTA),
IDVENTAITEM INT NOT NULL FOREIGN KEY REFERENCES VENTAITEMS(IDVENTAITEM),
PRIMARY KEY(IDVENTA,IDVENTAITEM)
)

GO

CREATE TABLE PERFILESUSUARIOS(
IDPERFILUSUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL
)

GO

CREATE TABLE USUARIOS(
IDUSUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
LOGUIN VARCHAR(50) NOT NULL,
IDPERFILUSUARIO INT NOT NULL FOREIGN KEY REFERENCES PERFILESUSUARIOS(IDPERFILUSUARIO)
)

--PERSONAS
INSERT INTO PERSONAS(NOMBRE,APELLIDO,DNI,TELEFONOFIJO,TELEFONOCELULAR,IDDOMICILIO,FECHANACIMIENTO,SEXO,EMAIL,CUIT) VALUES('ejemplo','bermudez',33265888,0114455986,1546897555,1,'02/10/1986','m','juancho2003@yahoo.com',20165552362)

--CLIENTE
INSERT INTO CLIENTES(IDPERSONA) VALUES(1)

--PROVEEDORES
INSERT INTO PROVEEDORES(NOMBRE,CUIT,IDDOMICILIO) VALUES('Ejemplo sa', 209996582, 1 )

--MARCAS
INSERT INTO MARCAS(NOMBRE)VALUES('Frititas')

--STOCK
INSERT INTO STOCK(ACTUAL, MINIMO) VALUES(40,10)

--TIPOPRODUCTO
INSERT INTO TIPOPRODUCTO(NOMBRE) VALUES('Galletas')

--PRODUCTO
INSERT INTO PRODUCTOS(IDTIPOPRODUCTO,IDMARCA,CODIGO,PRECIOCOSTO,PRECIOVENTA,IDSTOCK) VALUES(1,1,'a',15,20,1)

--PROVEEDORES_X_PRODUCTO
INSERT INTO PROVEEDORES_X_PRODUCTO(IDPROVEEDOR, IDPRODUCTO) VALUES(1,1)

--FACTURAS
INSERT INTO FACTURAS(FECHA, IDCLIENTE) VALUES('20/09/2018',1)

--DOMICILIO
INSERT INTO DOMICILIOS(CALLE,LOCALIDAD,PROVINCIA,CP,PAIS) VALUES('GARCIA 779','GARIN','BUENOS AIRES','1623','ARGENTINA')

--REGISTROCOMPRAS
INSERT INTO REGISTROCOMPRAS(NUMERO,FECHA,IDPROVEEDOR) VALUES(1,'16/09/2018',1)

--COMPRAITEMS
INSERT INTO COMPRAITEMS(IDCOMPRA,IDPRODUCTO,CANTIDAD,PRECIOCOMPRA) VALUES(1,1,2,15)

--REGISTROVENTAS
INSERT INTO REGISTROVENTAS(NUMERO,IDCLIENTE,FECHA,TOTAL,IDFACTURACION) VALUES(1,1,'20/09/2018',20,1)

--VENTAITEMS
INSERT INTO VENTAITEMS(IDVENTA,IDPRODUCTO,CANTIDAD,PRECIOUNITARIO,PRECIOPARCIAL) VALUES(1,1,30,20,40)

--REGISTROCOMPRAS_X_COMPRAITEMS
INSERT INTO REGISTROCOMPRAS_X_COMPRAITEMS(IDCOMPRA,IDCOMPRAITEM) VALUES(1,1)

--REGISTROVENTAS_X_VENTAITEMS
INSERT INTO REGISTROVENTAS_X_VENTAITEMS(IDVENTA,IDVENTAITEM) VALUES(1,1)

--PERFILESUSUARIOS
INSERT INTO PERFILESUSUARIOS(NOMBRE)VALUES('JUAN')

--USUARIOS
INSERT INTO USUARIOS(LOGUIN,IDPERFILUSUARIO)VALUES('PEPE123',1)